"""Add impersonal for ItemDetail

Revision ID: c15415105b56
Revises: 
Create Date: 2025-04-03 17:53:03.925474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15415105b56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_details', sa.Column('impersonal', sa.Integer(), nullable=True))
    # passitem_details
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    op.drop_column('item_details', 'impersonal')
    # ### end Alembic commands ###
